# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b384130b348647067ce509dde273df035de5f9fbaa87ab6cd449b2a4147fdfa78e0ef1b93ff802cdd05bd05253c39b8bdb604638c66e82fb223b747aeade5ac

test:
  secret_key_base: 2fe9aa54c30897368ef264465db27494b0a4590f8cb5188210e3c9d70d3098f83c42e49edc329eb4b1c63751a601c24ef4a586a2d919adc6fb2f656626ed6ebf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
